### ISSUE TITLE
stack-builder is not in docker-compose.yml

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/app-bdi-ide#5]
Hi @langens-jonathan,

I was following your instructions from the recent call to install bdi ide:
* Clone the integrator: https://github.com/big-data-europe/app-bdi-ide
* Clone the stack builder frontend: https://github.com/big-data-europe/ember-stack-builder-frontend
* cd ember-stack-builder-frontend && git checkout mock-hinting
* Modify in the integrator's docker-compose.yml:
```
stack-builder:	
	  # image: bde2020/ember-stack-builder-frontend:0.3.2
	  build: <path-to>/ember-stack-builder-frontend
```
* drc up

There is no stack-builder service in docker-compose.yml. I've checked both master and volume-fix branch. Can you please add it there?

**Comment by fr0gs** [comment]
Hello @earthquakesan,

In **app-bdi-ide** we make use of the **app-integrator-ui** image as the common frontend that encompasses all the subfrontends, as we add them as ember engines (ember addons).

```
app-integrator-ui/
   node_modules/
       ember-swarm-ui-engine/
       ... other frontends.
```
You can check it here: [https://github.com/big-data-europe/app-bdi-ide#how-to-add-new-services-ember-engines](https://github.com/big-data-europe/app-bdi-ide#how-to-add-new-services-ember-engines).

Additionally, we dropped the use of the **ember-stack-builder-frontend** a while ago in favor of the **ember-stack-builder-engine**.

Could you please link to the documentation piece where those instructions are reflected? Perhaps we forgot to update it somewhere.

Thank you!

**Comment by earthquakesan** [comment]
@fr0gs, does it mean that ember-stack-builder-frontend is packed together with integrator-ui service atm?

P.S. Anyway, it works, I am closing this issue.

**Comment by fr0gs** [comment]
It means that the ember-stack-builder-frontend is no longer maintained. Along with the integrator-ui you can see in the package.json file the ember-stack-builder-engine being added as a dependency.
